# Small VT-Former for testing and prototyping
# ~50M parameters, suitable for single GPU

name: vt_former_small

# Input dimensions
img_size: [256, 256, 64]  # H, W, D (reduced for testing)
patch_size: [16, 16, 8]   # Spatial patch size
in_channels: 1            # Grayscale fluorescence

# Model architecture
embed_dim: 512            # Hidden dimension
depth: 6                  # Number of transformer blocks
num_heads: 8              # Attention heads
mlp_ratio: 4.0           # MLP expansion ratio

# Temporal
temporal_resolution: 16   # Max frames in one forward pass
attention_type: divided   # 'divided' or 'joint'

# Regularization
dropout: 0.1
attention_dropout: 0.1
path_dropout: 0.1

# Initialization
init_std: 0.02
